version: '3.5'

services:
    web:
        image:  ${DOCKER_IMAGE-alexheld/website:latest}
        build:
            dockerfile: build/app.Dockerfile
            context:    .
        ports:
            - "8080:8080"
        environment:
            - REPO=github.com/alex-held/website
            - GIN_MODE=debug

